stages:
  - test
  - build
  - docker

test_job:
  stage: test
  image: golang:1.23
  script:
    - cd services/tasks
    - go mod tidy
    - go test ./...

build_job:
  stage: build
  image: golang:1.23
  script:
    - cd services/tasks
    - go build ./...

docker_job:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd services/tasks
    - docker build -t techip-tasks:$CI_COMMIT_SHORT_SHA .
